<a href="https://colab.research.google.com/github/smritigithubacc/Recommendation-systems/blob/main/Book_recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Collecting pandas
  Downloading pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 22.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Collecting tzdata>=2022.1 (from pandas)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 21.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible.
Successfully installed pandas-2.0.3 tzdata-2023.3

**FEATURE ENGINEERING**

In [ ]:
books = pd.read_csv('BX-Books.csv', sep=";", on_bad_lines='skip', encoding='latin-1', quotechar='"')

<ipython-input-2-0695649f423b>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('BX-Books.csv', sep=";", on_bad_lines='skip', encoding='latin-1', quotechar='"')

In [ ]:
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...

In [ ]:
books.columns
books=books[['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher']]
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner

In [ ]:
books.rename(columns={'Book-Title':'Title','Book-Author':'Author'},inplace=True)

In [ ]:
books.head(10)

,ISBN,Title,Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner

In [ ]:
users=pd.read_csv('BX-Users.csv',sep=";", on_bad_lines='skip', encoding='latin-1', quotechar='"')

In [ ]:
users.head(10)

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN
5        6       santa monica, california, usa  61.0
6        7                 washington, dc, usa   NaN
7        8            timmins, ontario, canada   NaN
8        9          germantown, tennessee, usa   NaN
9       10          albacete, wisconsin, spain  26.0

In [ ]:
users.rename(columns={'User-ID':'User_id'},inplace=True)
users.head(10)

   User_id                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN
5        6       santa monica, california, usa  61.0
6        7                 washington, dc, usa   NaN
7        8            timmins, ontario, canada   NaN
8        9          germantown, tennessee, usa   NaN
9       10          albacete, wisconsin, spain  26.0

In [ ]:
ratings=pd.read_csv('BX-Book-Ratings.csv',sep=";", on_bad_lines='skip', encoding='latin-1', quotechar='"')

In [ ]:
ratings.head(10)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6
5   276733  2080674722            0
6   276736  3257224281            8
7   276737  0600570967            6
8   276744  038550120X            7
9   276745   342310538           10

In [ ]:
books.shape

(271360, 5)

In [ ]:
users.shape

(278858, 3)

In [ ]:
ratings.shape

(1149780, 3)

APPLYING CONSTRAINTS ON USERS AND BOOKS
USERS-ONLY THOSE USERS WHO HAVE RATED ATLEAST 200 BOOKS
BOOKS- ONLY THOSE BOOKS WHICH HAVE BEEN RATED BY ATLEAST 50 USERS

In [ ]:
x=ratings['User-ID'].value_counts()>200

In [ ]:
x[x]

User-ID
11676     True
198711    True
153662    True
98391     True
35859     True
          ...
274808    True
28634     True
59727     True
268622    True
188951    True
Name: count, Length: 899, dtype: bool

In [ ]:
y=x[x].index

In [ ]:
print(y)

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727, 268622,
       188951],
      dtype='int64', name='User-ID', length=899)

In [ ]:
ratings=ratings[ratings['User-ID'].isin(y)]

In [ ]:
ratings.shape   #these 900 have done 5 lakh ratings

(526356, 3)

In [ ]:
ratings.head(10)

      User-ID        ISBN  Book-Rating
1456   277427  002542730X           10
1457   277427  0026217457            0
1458   277427  003008685X            8
1459   277427  0030615321            0
1460   277427  0060002050            0
1461   277427  0060006641           10
1462   277427  0060159685            0
1463   277427  0060177721            0
1464   277427  0060192704            0
1465   277427  0060542128            7

In [ ]:
books.head(10)

,ISBN,Title,Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner

In [ ]:
books.isnull().sum()

ISBN                   0
Title                  0
Author                 2
Year-Of-Publication    0
Publisher              2
dtype: int64

In [ ]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [ ]:
rating_withbooks=ratings.merge(books, on='ISBN')
rating_withbooks

,User-ID,ISBN,Book-Rating,Title,Author,Year-Of-Publication,Publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
...,...,...,...,...,...,...,...
487666,275970,1892145022,0,Here Is New York,E. B. White,1999,Little Bookroom
487667,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA)
487668,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim"
487669,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann
487670,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN)

In [ ]:
rating_withbooks.shape

(487671, 7)

In [ ]:
number_rating=rating_withbooks.groupby('Title')['Book-Rating'].count().reset_index()
number_rating

                                                    Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            2
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Beyond IBM: Leadership Marketing and Finance ...            1
4        Clifford Visita El Hospital (Clifford El Gran...            1
...                                                   ...          ...
160264  Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...            3
160265                                      Ã?Â?lpiraten.            1
160266                     Ã?Â?rger mit Produkt X. Roman.            1
160267                              Ã?Â?stlich der Berge.            1
160268                                  Ã?Â?thique en toc            1

[160269 rows x 2 columns]

In [ ]:
number_rating.rename(columns={'Book-Rating':'number of ratings'},inplace=True)
number_rating

                                                    Title  number of ratings
0        A Light in the Storm: The Civil War Diary of ...                  2
1                                   Always Have Popsicles                  1
2                    Apple Magic (The Collector's series)                  1
3        Beyond IBM: Leadership Marketing and Finance ...                  1
4        Clifford Visita El Hospital (Clifford El Gran...                  1
...                                                   ...                ...
160264  Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...                  3
160265                                      Ã?Â?lpiraten.                  1
160266                     Ã?Â?rger mit Produkt X. Roman.                  1
160267                              Ã?Â?stlich der Berge.                  1
160268                                  Ã?Â?thique en toc                  1

[160269 rows x 2 columns]

In [ ]:
final_rating=number_rating.merge(rating_withbooks,on='Title')
final_rating

,Title,number of ratings,User-ID,ISBN,Book-Rating,Author,Year-Of-Publication,Publisher
0,A Light in the Storm: The Civil War Diary of ...,2,35859,0590567330,0,Karen Hesse,1999,Hyperion Books for Children
1,A Light in the Storm: The Civil War Diary of ...,2,96448,0590567330,9,Karen Hesse,1999,Hyperion Books for Children
2,Always Have Popsicles,1,172742,0964147726,0,Rebecca Harvin,1994,Rebecca L. Harvin
3,Apple Magic (The Collector's series),1,198711,0942320093,0,Martina Boudreau,1984,Amer Cooking Guild
4,Beyond IBM: Leadership Marketing and Finance ...,1,11601,0962295701,0,Lou Mobley,1989,"Teleonet, Incorporated"
...,...,...,...,...,...,...,...,...
487666,Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...,3,173632,3257700512,0,Henry David Thoreau,1996,Diogenes
487667,Ã?Â?lpiraten.,1,11676,3499232499,0,Janwillem van de Wetering,2002,Rowohlt Tb.
487668,Ã?Â?rger mit Produkt X. Roman.,1,133567,325721538X,8,Joan Aiken,1987,Diogenes Verlag
487669,Ã?Â?stlich der Berge.,1,261105,3442725739,0,David Guterson,2000,btb
487670,Ã?Â?thique en toc,1,53628,2842192508,0,Didier Daeninckx,1998,Baleine

In [ ]:
final_rating=final_rating[final_rating['number of ratings']>50]
final_rating

,Title,number of ratings,User-ID,ISBN,Book-Rating,Author,Year-Of-Publication,Publisher
1073,1984,76,254,0451524934,9,George Orwell,1990,Signet Book
1074,1984,76,11676,0451524934,0,George Orwell,1990,Signet Book
1075,1984,76,12538,0451524934,0,George Orwell,1990,Signet Book
1076,1984,76,15408,0451524934,9,George Orwell,1990,Signet Book
1077,1984,76,16795,0451524934,8,George Orwell,1990,Signet Book
...,...,...,...,...,...,...,...,...
487432,"\O\"" Is for Outlaw""",105,234359,0805059555,0,Sue Grafton,1999,Henry Holt &amp; Company
487433,"\O\"" Is for Outlaw""",105,234623,0805059555,0,Sue Grafton,1999,Henry Holt &amp; Company
487434,"\O\"" Is for Outlaw""",105,236283,0805059555,10,Sue Grafton,1999,Henry Holt &amp; Company
487435,"\O\"" Is for Outlaw""",105,238120,0805059555,0,Sue Grafton,1999,Henry Holt &amp; Company
487436,"\O\"" Is for Outlaw""",105,254899,0805059555,0,Sue Grafton,1999,Henry Holt &amp; Company

In [ ]:
final_rating.shape

(59903, 8)

In [ ]:
final_rating.drop_duplicates(['User-ID','Title'],inplace=True)

<ipython-input-55-ae7972abe3b8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['User-ID','Title'],inplace=True)

In [ ]:
final_rating.shape

(57952, 8)

In [ ]:
book_pivot=final_rating.pivot_table(columns='User-ID',index='Title',values='Book-Rating')
book_pivot

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
book_pivot.fillna(0,inplace=True)
book_pivot

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from scipy.sparse import csr_matrix
book_sparse=csr_matrix(book_pivot)

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
model=NearestNeighbors(algorithm='brute')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [ ]:
distances,suggestions=model.kneighbors(book_pivot.iloc[240,:].values.reshape(1,-1),n_neighbors=6)

In [ ]:
suggestions

array([[237, 173, 277, 356, 507, 296]])

In [ ]:
distances

array([[ 0.        , 21.77154106, 23.91652149, 24.65765601, 25.05992817,
        25.3179778 ]])

In [ ]:
for i in range(len(suggestions)):
  print(book_pivot.index[suggestions[i]])

Index(['Hideaway', 'Dragon Tears', 'Sole Survivor', 'No Safe Place',
       'Exclusive', 'Winter Moon'],
      dtype='object', name='Title')

In [ ]:
book_pivot.index[240]

'Hideaway'

In [ ]:
def recommend_book(book_name):
  book_id=np.where(book_pivot.index==book_name)[0][0]
  distances,suggestions=model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors=6)
  for i in range(len(suggestions)):
    if i==0:
      print("the suggestions for" ,book_name, "are:")
    if not i:
      print(book_pivot.index[suggestions[i]])

In [ ]:
recommend_book('Hideaway')

the suggestions for Hideaway are:
Index(['Hideaway', 'Dragon Tears', 'Sole Survivor', 'No Safe Place',
       'Exclusive', 'Winter Moon'],
      dtype='object', name='Title')